### ISSUE TITLE
Build issues on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by tommythorn** [UCIS/QuickTun#3]
Building with `./build.sh` fails with

```
Detected Mac OS X (Darwin)
Cleaning up...
Creating source archive...
tar: Option --transform is not supported
Usage:
```
as Mac OS X tar doesn't support this flag.  Installing GNU tar (gnu-tar) via MacPorts and applying
```
diff --git a/build.sh b/build.sh
index 1467c9a..f8afa3e 100755
--- a/build.sh
+++ b/build.sh
@@ -17,6 +17,7 @@ elif [ "$(uname -s)" = "Darwin" ]; then
        echo "Detected Mac OS X (Darwin)"
        CFLAGS="$CFLAGS -arch i686"
        LDFLAGS="$LDFLAGS -arch i686"
+       tar=gtar
 fi

 echo Cleaning up...
```
get's us to
```
Building combined binary...
In file included from src/proto.raw.c:26:
src/common.c:48:11: fatal error: 'net/if_tun.h' file not found
        #include <net/if_tun.h>
                 ^
1 error generated.
```

The naive `brew install tuntap` failed with 
```
tuntap: Building this formula from source isn't possible due to OS X
Yosemite and above's strict unsigned kext ban.

You can install with Homebrew Cask:
  brew install Caskroom/cask/tuntap

You can download from:
  http://sourceforge.net/projects/tuntaposx/files/tuntap/
```

but alas `brew install Caskroom/cask/tuntap` doesn't come with `if_tun.h` nor
is it present in the sources at `http://sourceforge.net/projects/tuntaposx/files/tuntap/`

**Comment by dalanmiller** [comment]
@tommythorn Did you get your issue fixed? Having something similar.

**Comment by tommythorn** [comment]
Looks like I left it at that.  On your prompting I dug a bit deeper and found https://sourceforge.net/p/tuntaposx/mailman/message/21840614/ the essence of which is "The tuntap implementation does not support the ioctl you're trying to use."  A similar issue was discussed here http://stackoverflow.com/questions/13035220/interfacing-with-tun-tap-for-mac-osx-lion-using-python which suggest we'd need to hack QuickTun to get  further.

The odd thing is that the sources does include fragments compiled on under `__APPLE__` yet
I don't see how this could ever have worked.

The flags QuickTun tries to use are implemented and documented on FreeBSD:
```
     TUNSIFMODE	 The argument should be a pointer to an int; its value must be
		 either IFF_POINTOPOINT or IFF_BROADCAST and should have
		 IFF_MULTICAST OR'd into the value if multicast	support is
		 required.  The	type of the corresponding ``tunN'' interface
		 is set to the supplied type.  If the value is outside the
		 above range, an EINVAL error is returned.  The interface must
		 be down at the time; if it is up, an EBUSY error is returned.

     TUNSIFHEAD	 The argument should be a pointer to an int; a non-zero value
		 turns off ``link-layer'' mode, and enables ``multi-af'' mode,
		 where every packet is preceded with a four byte address family.
```
both of which sounds possible to work around.  As of right now, this is where I stopped.

**Comment by rotty** [comment]
Just out of curiosity (I'm don't use nor have access to Darwin-based devices): does pull request #2 solve this issue?

**Comment by tommythorn** [comment]
Yes, (after a `sed s/gnutar/gtar/ -i build.sh`).  The resulting executable appears to run, but
I haven't actually tested that it worked.

Thanks for pointing it out. I missed the pull request.  Wonder why it wasn't accepted.

**Comment by rotty** [comment]
Cool that you could verify that the change worked! In theory, the issue should still be open, as the pull request is not yet merged.

It seems to me that @UCIS is MIA, so I have intentions of collecting changes from the various forks, clean them up a bit, and then ask @UCIS how he feels about me releasing a new Quicktun version based on that. You can see my current progress at <http://rotty.xx.vu/git/mirrors/QuickTun/log/?h=wip/debian>. (Note that all branches prefixed with "wip/" are subject to random rebasing).

**Comment by rotty** [comment]
And @tommythorn, it would be really helpful if you could try the current wip/debian head revison of my repo. It contains the __APPLE__ patch that fixed your issue, and also has a completely reworked buildsystem, which should support Darwin, but has not yet seen a build there, as far as I'm aware ;-).

**Comment by UCIS** [comment]
@rotty @tommythorn I'm still alive, but have been very busy with work and other projects recently. I will try to take a look at the patch(es) in the next few days and see if we can merge them with minimal changes and perhaps without changing existing behavior.

**Comment by rotty** [comment]
@UCIS Excellent! I'm look forward to getting comments on my pull request, I'll post some new ones after we see how the buildsystem change works out.

**Comment by luckypoem** [comment]
@rotty 
i cloned ur repo,but ur repo also doesn't support compilation on mac:
yudeMacBook-Air:QuickTun-by-rotty brite$ ls
build.sh	clean.sh	debian		src		version
yudeMacBook-Air:QuickTun-by-rotty brite$ sh build.sh
Detected Mac OS X (Darwin)
Cleaning up...
Creating source archive...
tar: Option --transform is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
yudeMacBook-Air:QuickTun-by-rotty brite$

so how to fix it?
